[project]
name = "aqstandards"
description = "What the Package Does (One Line, Title Case)"

[dependencies]
dplyr = "*"
lubridate = "*"
purrr = "*"
rlang = "*"
stats = "*"
stringr = "*"
tidyr = "*"

[dev-dependencies]
testthat = ">=3.0.0"

[dev-dependencies.handyr]
git = "B-Nilson/handyr"
