test_that("the committed CAAQS fixture specification matches a fresh regeneration", {
  # The specification document is generated by running the fixture scenarios
  # against the package on disk (data-raw/CAAQS-regression-fixtures.R). This
  # test re-runs the generator and asserts the committed document still
  # matches, so the specification cannot silently rot after the branch it
  # was committed on. Line endings need no special handling: both copies are
  # read the same way, and git's EOL normalization applies to the checkout
  # the generator is compared against.
  # testthat runs with the working directory at tests/testthat; the
  # generator resolves its paths from the package root.
  pkg_root <- normalizePath(test_path("..", ".."))
  # Installed trees (R CMD INSTALL) and R CMD check do not ship data-raw/,
  # so the generator is only available in a source checkout. Skip rather
  # than error there; the enforcement still runs in source mode.
  skip_if_not(
    file.exists(file.path(pkg_root, "data-raw", "CAAQS-regression-fixtures.R")),
    "source checkout only: data-raw/ is not shipped in installed trees"
  )
  doc <- file.path(pkg_root, "data-raw", "CAAQS-regression-fixtures.md")
  expected <- readLines(doc, warn = FALSE)

  old_wd <- setwd(pkg_root)
  on.exit(setwd(old_wd), add = TRUE)
  status <- suppressWarnings(system2(
    "Rscript",
    "data-raw/CAAQS-regression-fixtures.R",
    stdout = FALSE,
    stderr = FALSE
  ))
  expect_identical(status, 0L, label = "generator exit status")

  actual <- readLines(doc, warn = FALSE)
  expect_identical(actual, expected)
})
